x-logging: &default-logging
  options:
    max-size: 50m
    max-file: 1
  driver: json-file

services:
  vpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    environment:
      FIREWALL: '' # Block all outbound traffic if the VPN is down.
    dns:
      - 1.1.1.1
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    volumes:
      - /dev/net:/dev/net:z
      - ./vpn:/vpn
    restart: always
    logging: *default-logging

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../config.yaml:/opt/app/config.yaml
    restart: always
    logging: *default-logging
    network_mode: "service:vpn"

  nginx:
    image: nginx
    depends_on:
      - app
    links:
      - vpn:app
    networks:
      - default
    ports:
      - 8080:8080
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf
    restart: always
    logging: *default-logging
